export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";


// table data 

export const GET_TABLE_DATA_REQUEST = "GET_TABLE_DATA_REQUEST";
export const GET_TABLE_DATA_SUCCESS = "GET_TABLE_DATA_SUCCESS";
export const GET_TABLE_DATA_FAIL = "GET_TABLE_DATA_FAIL";
// add user data
export const ADDUSER_DATA_REQUEST = "ADDUSER_DATA_REQUEST";
export const ADDUSER_DATA_SUCCESS = "ADDUSER_DATA_SUCCESS";
export const ADDUSER_DATA_FAIL = "ADDUSER_DATA_FAIL";
